name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
        - {cc: gcc-10, cxx: g++-10, config: Debug, cmake_args: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-march=skylake -Og -gsplit-dwarf"}
        - {cc: gcc-10, cxx: g++-10, config: Release, cmake_args: -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_LTO=On -DLLVM_ENABLE_LLD=OFF DCMAKE_CXX_FLAGS="-march=skylake -g1 -gdwarf-5 -Wsuggest-final-types"}
        - {cc: clang, cxx: clang++, config: Debug, cmake_args: -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-march=skylake -Og -gsplit-dwarf" }
        - {cc: clang, cxx: clang++, config: Release, cmake_args: -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_LTO=Thin -DCMAKE_CXX_FLAGS="-march=skylake -g1" -DCMAKE_EXE_LINKER_FLAGS="-gsplit-dwarf -fuse-ld=lld -Xlinker --thinlto-cache-dir=/tmp/thinltocache" -DCMAKE_SHARED_LINKER_FLAGS="-gsplit-dwarf -fuse-ld=lld -Xlinker --thinlto-cache-dir=/tmp/thinltocache" }

    steps:
    - uses: actions/checkout@v2
    - uses: Trass3r/setup-cpp@master
    - run: sudo apt install -y build-essential g++-10 binutils-dev cmake ninja-build clang lld python3 ccache
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      run: echo "::set-output name=date::`date -u +"%Y%m%d-%H%M%S"`"

    - name: restore ccache cache
      uses: actions/cache@v2
      with:
        path: build/.ccache
        key: ${{ matrix.config.cc }}-${{ matrix.config.config }}-ccache-${{ steps.ccache_cache_timestamp.outputs.date }}
        restore-keys: ${{ matrix.config.cc }}-${{ matrix.config.config }}-ccache-
    - name: restore thinlto cache
      uses: actions/cache@v2
      with:
        path: /tmp/thinltocache
        key: ${{ matrix.config.cc }}-${{ matrix.config.config }}-thinlto-${{ steps.ccache_cache_timestamp.outputs.date }}
        restore-keys: ${{ matrix.config.cc }}-${{ matrix.config.config }}-thinlto-
    - name: build
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
        CCACHE_DIR: ${{ github.workspace }}/build/.ccache
        CCACHE_BASEDIR: ${{ github.workspace }}
        #CCACHE_DEBUG: 1
        CCACHE_LOGFILE: /tmp/ccache.log
        CCACHE_MAXSIZE: 3G
      run: |
        mkdir -p build && cd build
        ccache -z
        cmake -G Ninja -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_DOCS=OFF -DCLANG_ENABLE_ARCMT=OFF -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;libclc;libcxx;libcxxabi;libunwind;lld;openmp;parallel-libs;pstl" -DCMAKE_INSTALL_PREFIX=/opt/clang -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON -DLLVM_BINUTILS_INCDIR=/usr/include -DLLVM_OPTIMIZED_TABLEGEN=ON -DLLVM_ENABLE_LLD=ON -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64;AMDGPU;NVPTX;RISCV;WebAssembly" -DLLVM_ENABLE_UNWIND_TABLES=OFF -DLLVM_ENABLE_DUMP=ON -DBUILD_SHARED_LIBS=ON ${{ matrix.config.cmake_args }} ../llvm/
        set +e
        ninja -k100
        ccache -s
        git clone --quiet --depth=1 https://github.com/nico/ninjatracing.git
        python3 ninjatracing/ninjatracing .ninja_log > buildtrace.json
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.cc }}-${{ matrix.config.config }}-ccache-debug
        path: |
          /tmp/ccache.log
          **/*.ccache-input-text
          **/*.ccache-log
    - name: install
      run: |
        cd build
        sudo ninja install
        sudo bash -c 'find /opt/clang -type f \( -executable -o -name \*.so\* \) -exec file --mime-type {} \; | egrep "x-(executable|sharedlib)" |  sed -r "s/(.+):[^:]+$/\1/" | xargs -t -n1 -P8 dwp -v -e' || true
    - name: separate debug info
      if: ${{ !contains(matrix.config.cmake_args, 'gsplit-dwarf') }}
      continue-on-error: true
      run: |
        sudo bash -c 'find /opt/clang -type f \( -executable -o -name \*.so\* \) -exec objcopy --only-keep-debug {} {}.dbg \; -exec strip --strip-debug --strip-unneeded {} \; -exec objcopy --add-gnu-debuglink={}.dbg {} \; -exec chmod -x {}.dbg \;'

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.cc }}-${{ matrix.config.config }}-trace
        path: build/buildtrace*
    - name: create tarball
      run: cd /opt/clang/ && tar cvapf "$GITHUB_WORKSPACE/clang.tar.xz" *
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.cc }}-${{ matrix.config.config }}-clang
        path: clang.tar.xz
