name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {cc: cl, cxx: cl, config: Release, cmake_args: -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS /W3 /D_HAS_EXCEPTIONS=0 /GR- /GS-" }

    steps:
    - uses: actions/checkout@v2
    - uses: Trass3r/setup-cpp@master
    - uses: ilammy/msvc-dev-cmd@v1
    - name: build
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: |
        mkdir build && cd build
        cmake -G Ninja -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_DOCS=OFF -DCLANG_ENABLE_ARCMT=OFF -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt" -DLLVM_OPTIMIZED_TABLEGEN=ON -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_UNWIND_TABLES=OFF -DBUILD_SHARED_LIBS=ON ${{ matrix.config.cmake_args }} ../llvm/
        ninja -k100
    - name: install
      run: |
        cd build
        ninja install
